import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import Header from "@/components/Header/Header";
import "./global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
      <Script
        dangerouslySetInnerHTML={{
          __html: `
        var wp_pp_gemius_identifier = 'coWacc7R.xHk.xzhRC.LgpQJ38OGWzuyOAxvi8UATAr.s7';
        var wp_sn = 'sg';
        var rekid = '7757';
        var wp_dot_type = 'click';`,
        }}
      />
      <Script
        dangerouslySetInnerHTML={{
          __html: `
          var WP = [];
          var wp_sn = 'sg';
          var wp_pp_gemius_identifier = 'coWacc7R.xHk.xzhRC.LgpQJ38OGWzuyOAxvi8UATAr.s7';
          WP.push(() => WP.stat.setDarkMode(true));
          WP.push(() => document.addEventListener('DOMContentLoaded', function () {
            setTimeout(function () {
              return false ||0==WP.cookie.get("ATT_IOS")||0==WP.cookie.get("ATT_AOS")||(WP.gdpr.get("ua")||WP.gdpr.check("mr","TP"))&&WP.gdpr.getConsentString()&&WP.gdpr.getHoldingState().keybase||WP.gdpr.showConsentForm();
            }, 50);
          }));
        `,
        }}
      />

      <Script src="https://std.wpcdn.pl/wpjslib/wpjslib-sgap.js" />
      <Script src="https://std.wpcdn.pl/wpjslib6/wpjslib-sgap.js" />
    </html>
  );
}
